{
 "title": "CaaSP Pods",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_annotations,namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"},pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\",pod=\"$pod\"},container)"
   },
   {
    "name": "pvc",
    "label": "PersistentVolumeClaim",
    "query": "label_values(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\", pod=\"$pod\"},persistentvolumeclaim)"
   }
  ]
 },
 "panels": [
  { "title": "INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Age",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - kube_pod_created{namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(kube_pod_container_status_ready{namespace=\"$namespace\",pod=\"$pod\"}) % 1"
    }
   ]
  },
  {
   "title": "IP address",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{pod_ip}}"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=\"$pod\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Owner",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count(kube_pod_owner{namespace=\"$namespace\", pod=\"$pod\"}) by  (owner_is_controller,namespace, owner_kind, owner_name)"
    }
   ]
  },
  {
   "title": "Containers / Images",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=\"$namespace\", pod=\"$pod\"}) by (container, image)"
    }
   ]
  },
  { "title": "MEMORY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "pod" },
  {
   "title": "Working Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod_name=~\"$pod\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod_name=~\"$pod\", container_name=\"POD\"}) by (pod_name, container_name)",
     "legendFormat": "└─ init"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod_name=~\"$pod\", container_name!=\"POD\"}) by (pod_name, container_name)",
     "legendFormat": "└─ {{container_name}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "pod" },
  {
   "title": "Working CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod_name=\"$pod\"}[5m]))",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container_name=\"POD\",pod_name=\"$pod\"}[5m])",
     "legendFormat": "└─ init"
    },
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container_name!=\"POD\", pod_name=\"$pod\"}[5m])",
     "legendFormat": "└─ {{container_name}}"
    }
   ]
  },
  { "title": "DISK I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{namespace=\"$namespace\", pod_name=\"$pod\", device=~\"(/dev/(sd|vd).*)\"}[5m])) by (device)",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=\"$namespace\", pod_name=\"$pod\", device=~\"(/dev/(sd|vd).*)\"}[5m])) by (device)",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod_name=\"$pod\", device=~\"(/dev/(sd|vd).*)\"}[5m])) by (device)",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod_name=\"$pod\", device=~\"(/dev/(sd|vd).*)\"}[5m])) by (device)",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_read_seconds_total{namespace=\"$namespace\", device=~\"(/dev/(sd|vd).*)\", pod_name=\"$pod\"} / container_fs_reads_total{namespace=\"$namespace\", device=~\"(/dev/(sd|vd).*)\", pod_name=\"$pod\"}) by (device, pod_name)",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "sum(container_fs_write_seconds_total{namespace=\"$namespace\", device=~\"(/dev/(sd|vd).*)\", pod_name=\"$pod\"} / container_fs_writes_total{namespace=\"$namespace\", device=~\"(/dev/(sd|vd).*)\", pod_name=\"$pod\"}) by (device, pod_name)",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  { "title": "NETWORK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Receive",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod_name=\"$pod\"}[5m])) by (interface, pod)",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Transmit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod_name=\"$pod\"}[5m])) by (interface, pod)",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  { "title": "VOLUMES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Volumes",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "count(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\", pod=\"$pod\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "count(kube_persistentvolumeclaim_info{namespace=\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) by(volumename)"
    },
    {
     "expr": "count(kube_persistentvolumeclaim_info{namespace=\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) by(storageclass)"
    },
    {
     "expr": "sum(kube_pod_spec_volumes_persistentvolumeclaims_readonly{namespace=\"$namespace\", pod=\"$pod\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$pvc\"})"
    }
   ]
  }
 ]
}