{
 "title": "CaaSP / Nodes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_exporter_build_info,instance)"
   }
  ]
 },
 "panels": [
  { "title": "OVERVIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "POD | NODE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$node\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "ARCH",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$node\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "UPTIME",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - (node_boot_time_seconds{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU CORES",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "max(count(node_cpu_seconds_total{instance=\"$node\"}) by (mode))"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "ROOT PART SIZE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "KERNEL",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$node\"}",
     "legendFormat": "{{exported_release}}"
    }
   ]
  },
  {
   "title": "TIME SYNC STATUS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_timex_sync_status{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "CURRENT CPU USAGE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(max(node_load1{instance=\"$node\"}) * 100) / (max(count(node_cpu_seconds_total{instance=\"$node\"}) by (mode)))"
    }
   ]
  },
  {
   "title": "CURRENT MEMORY USAGE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\"} / node_memory_MemTotal_bytes{instance=\"$node\"}) * 100)"
    }
   ]
  },
  {
   "title": "CURRENT PART UTILIZATION",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"} / node_filesystem_size_bytes{instance=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"}) * 100)"
    }
   ]
  },
  { "title": "MEMORY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "MEMORY USAGE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\"} / node_memory_MemTotal_bytes{instance=\"$node\"}) * 100)",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "MEMORY TOTAL",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 18, "y": 10 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "CURRENT MEMORY USAGE",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\"} / node_memory_MemTotal_bytes{instance=\"$node\"}) * 100)"
    }
   ]
  },
  {
   "title": "MEMORY INFO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"$node\"}",
     "legendFormat": "active"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$node\"}",
     "legendFormat": "available"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\"}",
     "legendFormat": "cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_Inactive_bytes{instance=\"$node\"}",
     "legendFormat": "inactive"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~'$node'} - node_memory_MemFree_bytes{instance=~'$node'}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~'$node'} - node_memory_MemAvailable_bytes{instance=~'$node'}",
     "legendFormat": "utilized"
    }
   ]
  },
  {
   "title": "MEMORY SATURATION",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_vmstat_pgpgin{instance=\"$node\"}[5m]) + irate(node_vmstat_pgpgout{instance=\"$node\"}[5m]))",
     "legendFormat": "saturation"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "SYSTEM LOAD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$node\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{instance=\"$node\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{instance=\"$node\"}",
     "legendFormat": "load15"
    },
    {
     "expr": "sum(node_load1{instance=\"$node\"}) by (instance) / count(node_cpu_seconds_total{instance=\"$node\", mode=\"system\"}) by (instance)",
     "legendFormat": "load1 ratio"
    },
    {
     "expr": "sum(node_load5{instance=\"$node\"}) by (instance) / count(node_cpu_seconds_total{instance=\"$node\", mode=\"system\"}) by (instance)",
     "legendFormat": "load5 ratio"
    },
    {
     "expr": "sum(node_load15{instance=\"$node\"}) by (instance) / count(node_cpu_seconds_total{instance=\"$node\", mode=\"system\"}) by (instance)",
     "legendFormat": "load15 ratio"
    }
   ]
  },
  {
   "title": "CPU CORES",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 18, "y": 32 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "max(count(node_cpu_seconds_total{instance=\"$node\"}) by (mode))"
    }
   ]
  },
  {
   "title": "CURRENT CPU USAGE",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 32 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(max(node_load1{instance=\"$node\"}) * 100) / (max(count(node_cpu_seconds_total{instance=\"$node\"}) by (mode)))"
    }
   ]
  },
  {
   "title": "SYSTEM LOAD PER MODE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode, instance) (irate(node_cpu_seconds_total{instance=\"$node\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "DISK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "ROOT PARTITION SPACE USAGE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"}",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "ROOT PART SIZE",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 18, "y": 47 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "CURRENT PART UTILIZATION",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 47 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"} / node_filesystem_size_bytes{instance=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"}) * 100)"
    }
   ]
  },
  {
   "title": "IOPS READ/WRITE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance='$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance='$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "IO LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~'$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m]) / irate(node_disk_reads_completed_total{instance=~'$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m])",
     "legendFormat": "{{device}}_avg_read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~'$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m]) / irate(node_disk_writes_completed_total{instance=~'$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m])",
     "legendFormat": "{{device}}_avg_write"
    }
   ]
  },
  {
   "title": "DISK THROUGHPUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance='$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance='$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  { "title": "NETWORK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "NETWORK IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\"}[5m])*8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "NETWORK OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\"}[5m])*8",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}