{
 "title": "CaaSP Nodes",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_exporter_build_info,kubernetes_node)"
   }
  ]
 },
 "panels": [
  { "title": "INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod | Node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_uname_info{kubernetes_node=\"$node\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_uname_info{kubernetes_node=\"$node\"}",
     "legendFormat": "{{exported_release}}"
    }
   ]
  },
  {
   "title": "Arch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_uname_info{kubernetes_node=\"$node\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - (node_boot_time_seconds{kubernetes_node=\"$node\"})"
    }
   ]
  },
  {
   "title": "Time Sync Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_timex_sync_status{kubernetes_node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=\"$node\"} - node_memory_MemAvailable_bytes{kubernetes_node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Working CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{kubernetes_node=\"$node\", mode!=\"idle\"}[5m])) by (kubernetes_node)"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "avg(count(node_cpu_seconds_total{kubernetes_node=\"$node\"}) by (mode))"
    }
   ]
  },
  {
   "title": "Root Partision Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{kubernetes_node=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"} - node_filesystem_avail_bytes{kubernetes_node=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Root Partition Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{kubernetes_node=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{kubernetes_node=\"$node\"} / node_memory_MemTotal_bytes{kubernetes_node=\"$node\"}) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum(irate(node_cpu_seconds_total{kubernetes_node=\"$node\", mode!=\"idle\"}[5m])) by (kubernetes_node)) * 100 / (avg(count(node_cpu_guest_seconds_total{kubernetes_node=\"$node\"}) by (mode)))"
    }
   ]
  },
  {
   "title": "Partition Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{kubernetes_node=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"} / node_filesystem_size_bytes{kubernetes_node=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"}) * 100)"
    }
   ]
  },
  { "title": "MEMORY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory Info",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{kubernetes_node=\"$node\"}",
     "legendFormat": "active"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{kubernetes_node=\"$node\"}",
     "legendFormat": "available"
    },
    {
     "expr": "node_memory_Cached_bytes{kubernetes_node=\"$node\"}",
     "legendFormat": "cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{kubernetes_node=\"$node\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_Inactive_bytes{kubernetes_node=\"$node\"}",
     "legendFormat": "inactive"
    },
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=~'$node'} - node_memory_MemFree_bytes{kubernetes_node=~'$node'}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=~'$node'} - node_memory_MemAvailable_bytes{kubernetes_node=~'$node'}",
     "legendFormat": "utilized"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{kubernetes_node=\"$node\"} / node_memory_MemTotal_bytes{kubernetes_node=\"$node\"}) * 100)",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_vmstat_pgpgin{kubernetes_node=\"$node\"}[5m]) + irate(node_vmstat_pgpgout{kubernetes_node=\"$node\"}[5m]))",
     "legendFormat": "saturation"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU Cores",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{kubernetes_node=\"$node\"}[5m])) by (mode)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{kubernetes_node=\"$node\", mode!=\"idle\"}[5m])) by (kubernetes_node)",
     "legendFormat": "working"
    }
   ]
  },
  {
   "title": "CPU Cores Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(sum(irate(node_cpu_seconds_total{kubernetes_node=\"$node\", mode!=\"idle\"}[5m])) by (kubernetes_node)) * 100 / (avg(count(node_cpu_guest_seconds_total{kubernetes_node=\"$node\"}) by (mode)))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{kubernetes_node=\"$node\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{kubernetes_node=\"$node\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{kubernetes_node=\"$node\"}",
     "legendFormat": "load15"
    },
    {
     "expr": "sum(node_load1{kubernetes_node=\"$node\"}) by (instance) / count(node_cpu_seconds_total{kubernetes_node=\"$node\", mode=\"system\"}) by (instance)",
     "legendFormat": "load1 ratio"
    },
    {
     "expr": "sum(node_load5{kubernetes_node=\"$node\"}) by (instance) / count(node_cpu_seconds_total{kubernetes_node=\"$node\", mode=\"system\"}) by (instance)",
     "legendFormat": "load5 ratio"
    },
    {
     "expr": "sum(node_load15{kubernetes_node=\"$node\"}) by (instance) / count(node_cpu_seconds_total{kubernetes_node=\"$node\", mode=\"system\"}) by (instance)",
     "legendFormat": "load15 ratio"
    }
   ]
  },
  { "title": "DISK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Root Partition Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{kubernetes_node=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"} - node_filesystem_avail_bytes{kubernetes_node=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_avail_bytes{kubernetes_node=\"$node\", device=~\"/dev/(sd|vd|rdb|hd)[a-z].*\", mountpoint=\"/\"}",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{kubernetes_node='$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{kubernetes_node='$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{kubernetes_node=~'$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m]) / irate(node_disk_reads_completed_total{kubernetes_node=~'$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m])",
     "legendFormat": "{{device}}_avg_read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{kubernetes_node=~'$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m]) / irate(node_disk_writes_completed_total{kubernetes_node=~'$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m])",
     "legendFormat": "{{device}}_avg_write"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{kubernetes_node='$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{kubernetes_node='$node', device=~\"(sd|vd|rdb|hd)[a-z].*\"}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  { "title": "NETWORK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Receive",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{kubernetes_node=\"$node\"}[5m])*8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{kubernetes_node=\"$node\"}[5m])*8",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}